### ISSUE TITLE
Entering idle state through a signal prevents taking a screenshot before locking

### ISSUE THREAD

**Issue by lo-zed** [jirutka/swaylock-effects#23]
# problem
Sending `SIGUSR1` to swayidle immediately enters idle state. Using this feature with swaylock-effects does not allow a screenshot to be taken.

# Environment
Archlinux 6.1.4-arch1-1
sway 1:1.8-3
swayidle 1.8.0-1
swaylock-effects-git r413.cd07dd1-1

# minimal example
```bash
swayidle -w timeout 300 'swaylock --screenshots' &
pkill -SIGUSR1 swayidle
```

# error
```
[main.c:653] Screencopy failed
[main.c:727] Failed to lock session -- is another lockscreen running?
```

# Closing
Thanks for your time.

**Comment by jirutka** [comment]
I think that this is now fixed (in 1.7.0.0), I couldn’t reproduce this issue in the latest version. Can you please test it?

**Comment by lo-zed** [comment]
Hi, sorry for my late reply.
Unfortunately, this still fails here. I'm now on 6.6.6-arch1-1 with
sway 1:1.8.1-4
swayidle 1.8.0-1
swaylock-effects-git r469.4f2234c-1
